<?php
return [
    'api/districts/list' => 'api/districts/list',

    'api/user/login' => 'api/user/login',
    'api/user/add' => 'api/user/add',
    'api/user/delete' => 'api/user/delete',
    'api/user/update' => 'api/user/update',
    'api/user/info' => 'api/user/info',
    'api/user/list' => 'api/user/list',
    'api/user/selectconfig' => 'api/user/selectconfig',
    'api/user/pwdupdate' => 'api/user/pwdupdate',
    'api/user/pwdreset' => 'api/user/pwdreset',
    'api/user/updaterole' => 'api/user/updaterole',
    'api/user/my' => 'api/user/my',
    'api/user/organsexcel' => 'api/user/organsexcel',
    'api/user/organsexcelupload' => 'api/user/organsexcelupload',
    'api/user/thirdpartexcel' => 'api/user/thirdpartexcel',
    'api/user/thirdpartexcelupload' => 'api/user/thirdpartexcelupload',

    'api/organization/add' => 'api/organization/add',
    'api/organization/addbyname' => 'api/organization/addbyname',
    'api/organization/multiadd' => 'api/organization/multiadd',
    'api/organization/info' => 'api/organization/info',
    'api/organization/update' => 'api/organization/update',
    'api/organization/search' => 'api/organization/search',
    'api/organization/delete' => 'api/organization/delete',
    'api/organization/list' => 'api/organization/list',
    'api/organization/users' => 'api/organization/users',
    'api/organization/departs' => 'api/organization/departs',

    'api/project/create' => 'api/project/create',
    'api/project/selectconfig' => 'api/project/selectconfig',
    'api/project/list' => 'api/project/list',
    'api/project/update' => 'api/project/update',
    'api/project/delete' => 'api/project/delete',
    'api/project/info' => 'api/project/info',
    'api/project/updatestatus' => 'api/project/updatestatus',
    'api/project/auditinfo' => 'api/project/auditinfo',
    'api/project/listselect' => 'api/project/listselect',
    'api/project/editinfo' => 'api/project/editinfo',
    'api/project/info' => 'api/project/info',

    'api/auditgroup/add' => 'api/auditgroup/add',
    'api/auditgroup/updaterole' => 'api/auditgroup/updaterole',
    'api/auditgroup/delete' => 'api/auditgroup/delete',
    'api/auditgroup/unlock' => 'api/auditgroup/unlock',
    'api/auditgroup/updatestatus' => 'api/auditgroup/updatestatus',
];
