<?php
return [
    'api/districts/list' => 'api/districts/list',

    'api/user/login' => 'api/user/login',
    'api/user/add' => 'api/user/add',
    'api/user/delete' => 'api/user/delete',
    'api/user/update' => 'api/user/update',
    'api/user/info' => 'api/user/info',
    'api/user/list' => 'api/user/list',
    'api/user/selectconfig' => 'api/user/selectconfig',
    'api/user/pwdupdate' => 'api/user/pwdupdate',
    'api/user/pwdreset' => 'api/user/pwdreset',
    'api/user/updaterole' => 'api/user/updaterole',
    'api/user/my' => 'api/user/my',
    'api/user/organsexcel' => 'api/user/organsexcel',
    'api/user/organsexcelupload' => 'api/user/organsexcelupload',
    'api/user/thirdpartexcel' => 'api/user/thirdpartexcel',
    'api/user/thirdpartexcelupload' => 'api/user/thirdpartexcelupload',

    'api/organization/add' => 'api/organization/add',
    'api/organization/addbyname' => 'api/organization/addbyname',
    'api/organization/multiadd' => 'api/organization/multiadd',
    'api/organization/info' => 'api/organization/info',
    'api/organization/update' => 'api/organization/update',
    'api/organization/search' => 'api/organization/search',
    'api/organization/delete' => 'api/organization/delete',
    'api/organization/list' => 'api/organization/list',
    'api/organization/users' => 'api/organization/users',
    'api/organization/departs' => 'api/organization/departs',
    'api/organization/listbytype' => 'api/organization/listbytype',
    'api/organization/subordinate' => 'api/organization/subordinate',
    'api/organization/excel' => 'api/organization/excel',
    'api/organization/excelupload' => 'api/organization/excelupload',

    'api/project/create' => 'api/project/create',
    'api/project/selectconfig' => 'api/project/selectconfig',
    'api/project/list' => 'api/project/list',
    'api/project/update' => 'api/project/update',
    'api/project/delete' => 'api/project/delete',
    'api/project/info' => 'api/project/info',
    'api/project/infolist' => 'api/project/infolist',
    'api/project/updatestatus' => 'api/project/updatestatus',
    'api/project/auditinfo' => 'api/project/auditinfo',
    'api/project/listselect' => 'api/project/listselect',
    'api/project/editinfo' => 'api/project/editinfo',
    'api/project/excel' => 'api/project/excel',
    'api/project/excelupload' => 'api/project/excelupload',

    'api/auditgroup/jugechange' => 'api/auditgroup/jugechange',
    'api/auditgroup/add' => 'api/auditgroup/add',
    'api/auditgroup/updaterole' => 'api/auditgroup/updaterole',
    'api/auditgroup/delete' => 'api/auditgroup/delete',
    'api/auditgroup/unlock' => 'api/auditgroup/unlock',
    'api/auditgroup/updatestatus' => 'api/auditgroup/updatestatus',
    'api/auditgroup/userlist' => 'api/auditgroup/userlist',
    'api/auditgroup/reviewadd' => 'api/auditgroup/reviewadd',
    'api/auditgroup/jugebind' => 'api/auditgroup/jugebind',
    'api/auditgroup/jugelist' => 'api/auditgroup/jugelist',
    'api/auditgroup/jugeunbind' => 'api/auditgroup/jugeunbind',
    'api/review/list' => 'api/review/list',
    'api/review/info' => 'api/review/info',
    'api/review/listsetting' => 'api/review/listsetting',
    'api/review/operate' => 'api/review/operate',
    'api/review/resultlist' => 'api/review/resultlist',
    'api/review/resultdetails' => 'api/review/resultdetails',
    'api/review/resultoperate' => 'api/review/resultoperate',

    'api/assess/statlist' => 'api/assess/statlist',
    'api/assess/form' => 'api/assess/form',
    'api/assess/submit' => 'api/assess/submit',
    'api/assess/assesstypes' => 'api/assess/assesstypes',
    'api/assess/scoreconfig' => 'api/assess/scoreconfig',
    'api/assess/saveconfig' => 'api/assess/saveconfig',
    'api/assess/deleteconfig' => 'api/assess/deleteconfig',
    'api/assess/violations' => 'api/assess/violations',

    'api/auditresults/details' => 'api/auditresults/details',
    'api/auditresults/search' => 'api/auditresults/search',
    'api/auditresults/saveresult' => 'api/auditresults/saveresult',
    'api/auditresults/submitresult' => 'api/auditresults/submitresult',
    'api/auditresults/delresult' => 'api/auditresults/delresult',
    'api/auditresults/excel' => 'api/auditresults/excel',
    'api/auditresults/excelupload' => 'api/auditresults/excelupload',
    'api/auditresults/projectlist' => 'api/auditresults/projectlist',

    'api/dashbord/expertise' => 'api/dashbord/expertise',

    'api/auth/list' => 'api/auth/list',
    'api/auth/update' => 'api/auth/update',
];
