<?php

return '[
{
    "name":"1.财政类",
    "id":"1",
    "type":"parent",
    "data":[
    ],
    "list":[
    {
        "name":"1.1.预算执行",
        "id":"6",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"1.1.1.违规金额",
            "id":"39",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.1.2.损失浪费金额",
            "id":"40",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.1.3.管理不规范金额",
            "id":"41",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.1.4.非金额计量问题",
            "id":"42",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"1.2.财政决算",
        "id":"7",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"1.2.1.违规金额",
            "id":"43",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.2.2.损失浪费金额",
            "id":"44",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.2.3.管理不规范金额",
            "id":"45",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.2.4.非金额计量问题",
            "id":"46",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"1.3.专项资金-教育",
        "id":"8",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"1.3.1.违规金额",
            "id":"47",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.3.2.损失浪费金额",
            "id":"48",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.3.3.管理不规范金额",
            "id":"49",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.3.4.非金额计量问题",
            "id":"50",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"1.4.专项资金-科学技术",
        "id":"9",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"1.4.1.违规金额",
            "id":"51",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.4.2.损失浪费金额",
            "id":"52",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.4.3.管理不规范金额",
            "id":"53",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.4.4.非金额计量问题",
            "id":"54",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"1.5.专项资金-文化体育",
        "id":"10",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"1.5.1.违规金额",
            "id":"55",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.5.2.损失浪费金额",
            "id":"56",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.5.3.管理不规范金额",
            "id":"57",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.5.4.非金额计量问题",
            "id":"58",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"1.6.专项资金-医疗卫生",
        "id":"11",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"1.6.1.违规金额",
            "id":"59",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.6.2.损失浪费金额",
            "id":"60",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.6.3.管理不规范金额",
            "id":"61",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.6.4.非金额计量问题",
            "id":"62",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"1.7.专项资金-节能环保",
        "id":"12",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"1.7.1.违规金额",
            "id":"63",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.7.2.损失浪费金额",
            "id":"64",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.7.3.管理不规范金额",
            "id":"65",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.7.4.非金额计量问题",
            "id":"66",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"1.8.专项资金-城乡社区",
        "id":"13",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"1.8.1.违规金额",
            "id":"67",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.8.2.损失浪费金额",
            "id":"68",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.8.3.管理不规范金额",
            "id":"69",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.8.4.非金额计量问题",
            "id":"70",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"1.9.专项资金-农林水",
        "id":"14",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"1.9.1.违规金额",
            "id":"71",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.9.2.损失浪费金额",
            "id":"72",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.9.3.管理不规范金额",
            "id":"73",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.9.4.非金额计量问题",
            "id":"74",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"1.10.专项资金-住房保障",
        "id":"15",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"1.10.1.违规金额",
            "id":"75",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.10.2.损失浪费金额",
            "id":"76",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.10.3.管理不规范金额",
            "id":"77",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.10.4.非金额计量问题",
            "id":"78",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"1.11.专项资金-其他",
        "id":"16",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"1.11.1.违规金额",
            "id":"79",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.11.2.损失浪费金额",
            "id":"80",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.11.3.管理不规范金额",
            "id":"81",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.11.4.非金额计量问题",
            "id":"82",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"1.12.投资",
        "id":"17",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"1.12.1.违规金额",
            "id":"83",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.12.2.损失浪费金额",
            "id":"84",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.12.3.管理不规范金额",
            "id":"85",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.12.4.非金额计量问题",
            "id":"86",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"1.13.国外代援款",
        "id":"18",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"1.13.1.违规金额",
            "id":"87",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.13.2.损失浪费金额",
            "id":"88",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.13.3.管理不规范金额",
            "id":"89",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.13.4.非金额计量问题",
            "id":"90",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"1.14.其他",
        "id":"19",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"1.14.1.违规金额",
            "id":"91",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.14.2.损失浪费金额",
            "id":"92",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.14.3.管理不规范金额",
            "id":"93",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"1.14.4.非金额计量问题",
            "id":"94",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    }
    ]
},
{
    "name":"2.社会保险基金类",
    "id":"2",
    "type":"parent",
    "data":[
    ],
    "list":[
    {
        "name":"2.1.养老保险",
        "id":"20",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"2.1.1.违规金额",
            "id":"95",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"2.1.2.损失浪费金额",
            "id":"96",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"2.1.3.管理不规范金额",
            "id":"97",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"2.1.4.非金额计量问题",
            "id":"98",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"2.2.失业、工伤、生育",
        "id":"21",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"2.2.1.违规金额",
            "id":"99",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"2.2.2.损失浪费金额",
            "id":"100",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"2.2.3.管理不规范金额",
            "id":"101",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"2.2.4.非金额计量问题",
            "id":"102",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"2.3.医疗保险",
        "id":"22",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"2.3.1.违规金额",
            "id":"103",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"2.3.2.损失浪费金额",
            "id":"104",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"2.3.3.管理不规范金额",
            "id":"105",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"2.3.4.非金额计量问题",
            "id":"106",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"2.4.住房公积金",
        "id":"23",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"2.4.1.违规金额",
            "id":"107",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"2.4.2.损失浪费金额",
            "id":"108",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"2.4.3.管理不规范金额",
            "id":"109",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"2.4.4.非金额计量问题",
            "id":"110",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"2.5.其他",
        "id":"24",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"2.5.1.违规金额",
            "id":"111",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"2.5.2.损失浪费金额",
            "id":"112",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"2.5.3.管理不规范金额",
            "id":"113",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"2.5.4.非金额计量问题",
            "id":"114",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    }
    ]
},
{
    "name":"3.企业金融类",
    "id":"3",
    "type":"parent",
    "data":[
    ],
    "list":[
    {
        "name":"3.1.企业类",
        "id":"25",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"3.1.1.违规金额",
            "id":"115",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"3.1.2.损失浪费金额",
            "id":"116",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"3.1.3.管理不规范金额",
            "id":"117",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"3.1.4.非金额计量问题",
            "id":"118",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"3.2.金融类",
        "id":"26",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"3.2.1.违规金额",
            "id":"119",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"3.2.2.损失浪费金额",
            "id":"120",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"3.2.3.管理不规范金额",
            "id":"121",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"3.2.4.非金额计量问题",
            "id":"122",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"3.3.其他",
        "id":"27",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"3.3.1.违规金额",
            "id":"123",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"3.3.2.损失浪费金额",
            "id":"124",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"3.3.3.管理不规范金额",
            "id":"125",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"3.3.4.非金额计量问题",
            "id":"126",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    }
    ]
},
{
    "name":"4.经济责任类",
    "id":"4",
    "type":"parent",
    "data":[
    ],
    "list":[
    {
        "name":"4.1.党政领导干部",
        "id":"28",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"4.1.1.违规金额",
            "id":"127",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"4.1.2.损失浪费金额",
            "id":"128",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"4.1.3.管理不规范金额",
            "id":"129",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"4.1.4.非金额计量问题",
            "id":"130",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"4.2.部门领导干部",
        "id":"29",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"4.2.1.违规金额",
            "id":"131",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"4.2.2.损失浪费金额",
            "id":"132",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"4.2.3.管理不规范金额",
            "id":"133",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"4.2.4.非金额计量问题",
            "id":"134",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"4.3.企业领导干部",
        "id":"30",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"4.3.1.违规金额",
            "id":"135",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"4.3.2.损失浪费金额",
            "id":"136",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"4.3.3.管理不规范金额",
            "id":"137",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"4.3.4.非金额计量问题",
            "id":"138",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"4.4.自然资源资产",
        "id":"31",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"4.4.1.违规金额",
            "id":"139",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"4.4.2.损失浪费金额",
            "id":"140",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"4.4.3.管理不规范金额",
            "id":"141",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"4.4.4.非金额计量问题",
            "id":"142",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"4.5.高校",
        "id":"32",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"4.5.1.违规金额",
            "id":"143",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"4.5.2.损失浪费金额",
            "id":"144",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"4.5.3.管理不规范金额",
            "id":"145",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"4.5.4.非金额计量问题",
            "id":"146",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"4.6.其他",
        "id":"33",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"4.6.1.违规金额",
            "id":"147",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"4.6.2.损失浪费金额",
            "id":"148",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"4.6.3.管理不规范金额",
            "id":"149",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"4.6.4.非金额计量问题",
            "id":"150",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    }
    ]
},
{
    "name":"5.政策跟踪",
    "id":"5",
    "type":"parent",
    "data":[
    ],
    "list":[
    {
        "name":"5.1.防范风险",
        "id":"34",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"5.1.1.违规金额",
            "id":"151",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"5.1.2.损失浪费金额",
            "id":"152",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"5.1.3.管理不规范金额",
            "id":"153",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"5.1.4.非金额计量问题",
            "id":"154",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"5.2.生态环保",
        "id":"35",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"5.2.1.违规金额",
            "id":"155",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"5.2.2.损失浪费金额",
            "id":"156",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"5.2.3.管理不规范金额",
            "id":"157",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"5.2.4.非金额计量问题",
            "id":"158",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"5.3.脱贫攻坚",
        "id":"36",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"5.3.1.违规金额",
            "id":"159",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"5.3.2.损失浪费金额",
            "id":"160",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"5.3.3.管理不规范金额",
            "id":"161",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"5.3.4.非金额计量问题",
            "id":"162",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"5.4.乡村振兴",
        "id":"37",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"5.4.1.违规金额",
            "id":"163",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"5.4.2.损失浪费金额",
            "id":"164",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"5.4.3.管理不规范金额",
            "id":"165",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"5.4.4.非金额计量问题",
            "id":"166",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    },
    {
        "name":"5.5.其他",
        "id":"38",
        "type":"parent",
        "data":[
        ],
        "list":[
        {
            "name":"5.5.1.违规金额",
            "id":"167",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"5.5.2.损失浪费金额",
            "id":"168",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"5.5.3.管理不规范金额",
            "id":"169",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        },
        {
            "name":"5.5.4.非金额计量问题",
            "id":"170",
            "type":"parent",
            "data":[
            ],
            "list":[
            ]
        }
        ]
    }
    ]
}
]';
